name: Tests

on: [pull_request]

jobs:
  teste:
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        with:
          python-version: '3.9.7'
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Teste
        run: |
          poetry run pytest -vvv
