name: Tests

on: [pull_request]

jobs:
  teste:
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry env use python3.9
          poetry install
      - name: Teste
        run: |
          poetry run pytest -vvv
